//! # geyser-tap-proto
//!
//! Protocol buffer definitions for geyser-tap streaming.
//!
//! This crate provides:
//! - Protobuf message types for all update kinds
//! - gRPC service definitions for streaming
//! - Conversion traits from internal types to protobuf
//!
//! ## Wire Format
//!
//! All messages are serialized using Protocol Buffers 3. The schema is
//! designed for:
//! - Efficient serialization with minimal allocations
//! - Forward/backward compatibility
//! - Easy consumption by polyglot clients
//!
//! ## Zero-Copy Strategy
//!
//! Where possible, we use `bytes::Bytes` to avoid copying large data
//! (account data, transaction payloads) during serialization.

#![deny(unsafe_op_in_unsafe_fn)]
#![warn(missing_docs, rust_2018_idioms)]

// Include generated protobuf code
// In a real build, this would be generated by build.rs
// For now, we define the module structure manually

pub mod geyser {
    //! Geyser streaming protocol definitions.

    // Types defined manually to avoid protoc dependency during cross-platform builds.
    // For production with tonic-build, use: include!(concat!(env!("OUT_DIR"), "/geyser.rs"));

    use bytes::Bytes;
    use prost::Message;

    /// Wrapper for all update types in a single stream message.
    #[derive(Clone, PartialEq, Message)]
    pub struct StreamUpdate {
        /// Sequence number for ordering
        #[prost(uint64, tag = "1")]
        pub sequence: u64,

        /// Timestamp when the update was received (nanoseconds since epoch)
        #[prost(uint64, tag = "2")]
        pub timestamp_ns: u64,

        /// The actual update payload
        #[prost(oneof = "UpdatePayload", tags = "10, 11, 12, 13, 14")]
        pub payload: Option<UpdatePayload>,
    }

    /// Discriminated union of all update types.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum UpdatePayload {
        /// Account update
        #[prost(message, tag = "10")]
        Account(AccountUpdate),

        /// Transaction update
        #[prost(message, tag = "11")]
        Transaction(TransactionUpdate),

        /// Slot update
        #[prost(message, tag = "12")]
        Slot(SlotUpdate),

        /// Entry update
        #[prost(message, tag = "13")]
        Entry(EntryUpdate),

        /// Block metadata update
        #[prost(message, tag = "14")]
        BlockMetadata(BlockMetadataUpdate),
    }

    /// Account data update.
    #[derive(Clone, PartialEq, Message)]
    pub struct AccountUpdate {
        /// Account public key (32 bytes)
        #[prost(bytes = "bytes", tag = "1")]
        pub pubkey: Bytes,

        /// Account data
        #[prost(bytes = "bytes", tag = "2")]
        pub data: Bytes,

        /// Slot at which this update occurred
        #[prost(uint64, tag = "3")]
        pub slot: u64,

        /// Account owner program (32 bytes)
        #[prost(bytes = "bytes", tag = "4")]
        pub owner: Bytes,

        /// Lamport balance
        #[prost(uint64, tag = "5")]
        pub lamports: u64,

        /// Rent epoch
        #[prost(uint64, tag = "6")]
        pub rent_epoch: u64,

        /// Whether the account is executable
        #[prost(bool, tag = "7")]
        pub executable: bool,

        /// Write version for ordering
        #[prost(uint64, tag = "8")]
        pub write_version: u64,

        /// Transaction signature that caused this update (64 bytes, optional)
        #[prost(bytes = "bytes", optional, tag = "9")]
        pub txn_signature: Option<Bytes>,
    }

    /// Transaction update.
    #[derive(Clone, PartialEq, Message)]
    pub struct TransactionUpdate {
        /// Transaction signature (64 bytes)
        #[prost(bytes = "bytes", tag = "1")]
        pub signature: Bytes,

        /// Serialized transaction
        #[prost(bytes = "bytes", tag = "2")]
        pub transaction: Bytes,

        /// Slot containing this transaction
        #[prost(uint64, tag = "3")]
        pub slot: u64,

        /// Index within the slot
        #[prost(uint64, tag = "4")]
        pub index: u64,

        /// Whether this is a vote transaction
        #[prost(bool, tag = "5")]
        pub is_vote: bool,

        /// Transaction metadata (serialized)
        #[prost(bytes = "bytes", optional, tag = "6")]
        pub meta: Option<Bytes>,
    }

    /// Slot status update.
    #[derive(Clone, PartialEq, Message)]
    pub struct SlotUpdate {
        /// Slot number
        #[prost(uint64, tag = "1")]
        pub slot: u64,

        /// Parent slot number (optional for genesis)
        #[prost(uint64, optional, tag = "2")]
        pub parent: Option<u64>,

        /// Slot status
        #[prost(enumeration = "SlotStatus", tag = "3")]
        pub status: i32,
    }

    /// Slot status enumeration.
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum SlotStatus {
        /// Unknown status
        Unknown = 0,
        /// Slot is being processed
        Processed = 1,
        /// Slot is rooted (finalized)
        Rooted = 2,
        /// Slot has been confirmed
        Confirmed = 3,
    }

    /// Entry update (batch of transactions within a slot).
    #[derive(Clone, PartialEq, Message)]
    pub struct EntryUpdate {
        /// Slot containing this entry
        #[prost(uint64, tag = "1")]
        pub slot: u64,

        /// Entry index within the slot
        #[prost(uint64, tag = "2")]
        pub index: u64,

        /// Number of hashes since previous entry
        #[prost(uint64, tag = "3")]
        pub num_hashes: u64,

        /// Entry hash (32 bytes)
        #[prost(bytes = "bytes", tag = "4")]
        pub hash: Bytes,

        /// Serialized entry data
        #[prost(bytes = "bytes", tag = "5")]
        pub entry: Bytes,

        /// Number of executed transactions
        #[prost(uint64, tag = "6")]
        pub executed_transaction_count: u64,
    }

    /// Block metadata update.
    #[derive(Clone, PartialEq, Message)]
    pub struct BlockMetadataUpdate {
        /// Slot number
        #[prost(uint64, tag = "1")]
        pub slot: u64,

        /// Block hash (32 bytes)
        #[prost(bytes = "bytes", tag = "2")]
        pub blockhash: Bytes,

        /// Block time (Unix timestamp)
        #[prost(int64, optional, tag = "3")]
        pub block_time: Option<i64>,

        /// Block height
        #[prost(uint64, optional, tag = "4")]
        pub block_height: Option<u64>,

        /// Rewards (serialized)
        #[prost(bytes = "bytes", optional, tag = "5")]
        pub rewards: Option<Bytes>,
    }

    /// Subscription request for the streaming service.
    #[derive(Clone, PartialEq, Message)]
    pub struct SubscribeRequest {
        /// Filter for account updates
        #[prost(message, optional, tag = "1")]
        pub accounts: Option<AccountFilter>,

        /// Filter for transaction updates
        #[prost(message, optional, tag = "2")]
        pub transactions: Option<TransactionFilter>,

        /// Whether to receive slot updates
        #[prost(bool, tag = "3")]
        pub slots: bool,

        /// Whether to receive entry updates
        #[prost(bool, tag = "4")]
        pub entries: bool,

        /// Whether to receive block metadata updates
        #[prost(bool, tag = "5")]
        pub block_metadata: bool,
    }

    /// Filter for account updates.
    #[derive(Clone, PartialEq, Message)]
    pub struct AccountFilter {
        /// Account owners to include (empty = all)
        #[prost(bytes = "bytes", repeated, tag = "1")]
        pub owners: Vec<Bytes>,

        /// Account pubkeys to include (empty = all)
        #[prost(bytes = "bytes", repeated, tag = "2")]
        pub pubkeys: Vec<Bytes>,
    }

    /// Filter for transaction updates.
    #[derive(Clone, PartialEq, Message)]
    pub struct TransactionFilter {
        /// Whether to include vote transactions
        #[prost(bool, tag = "1")]
        pub include_votes: bool,

        /// Whether to include failed transactions
        #[prost(bool, tag = "2")]
        pub include_failed: bool,

        /// Account keys that must be involved in the transaction
        #[prost(bytes = "bytes", repeated, tag = "3")]
        pub account_keys: Vec<Bytes>,
    }

    /// Ping request for health checking.
    #[derive(Clone, PartialEq, Message)]
    pub struct PingRequest {
        /// Client timestamp in nanoseconds
        #[prost(uint64, tag = "1")]
        pub timestamp_ns: u64,
    }

    /// Ping response for health checking.
    #[derive(Clone, PartialEq, Message)]
    pub struct PingResponse {
        /// Echo of client timestamp
        #[prost(uint64, tag = "1")]
        pub client_timestamp_ns: u64,

        /// Server timestamp in nanoseconds
        #[prost(uint64, tag = "2")]
        pub server_timestamp_ns: u64,

        /// Current slot being processed
        #[prost(uint64, tag = "3")]
        pub current_slot: u64,
    }
}

/// Conversion implementations from internal types to protobuf.
pub mod convert {

    use super::geyser;
    use bytes::Bytes;
    use geyser_tap_common::{
        AccountUpdate, BlockMetadataUpdate, EntryUpdate, SlotStatus, SlotUpdate,
        TransactionUpdate, Update,
    };

    impl From<&AccountUpdate> for geyser::AccountUpdate {
        fn from(update: &AccountUpdate) -> Self {
            Self {
                pubkey: Bytes::copy_from_slice(&update.pubkey),
                data: update.data.clone(),
                slot: update.slot,
                owner: Bytes::copy_from_slice(&update.owner),
                lamports: update.lamports,
                rent_epoch: update.rent_epoch,
                executable: update.executable,
                write_version: update.write_version,
                txn_signature: update
                    .txn_signature
                    .map(|s| Bytes::copy_from_slice(&s)),
            }
        }
    }

    impl From<&TransactionUpdate> for geyser::TransactionUpdate {
        fn from(update: &TransactionUpdate) -> Self {
            Self {
                signature: Bytes::copy_from_slice(&update.signature),
                transaction: update.transaction_data.clone(),
                slot: update.slot,
                index: update.index,
                is_vote: update.is_vote,
                meta: update.meta.clone(),
            }
        }
    }

    impl From<SlotStatus> for geyser::SlotStatus {
        fn from(status: SlotStatus) -> Self {
            match status {
                SlotStatus::Processed => geyser::SlotStatus::Processed,
                SlotStatus::Rooted => geyser::SlotStatus::Rooted,
                SlotStatus::Confirmed => geyser::SlotStatus::Confirmed,
            }
        }
    }

    impl From<&SlotUpdate> for geyser::SlotUpdate {
        fn from(update: &SlotUpdate) -> Self {
            Self {
                slot: update.slot,
                parent: update.parent,
                status: geyser::SlotStatus::from(update.status) as i32,
            }
        }
    }

    impl From<&EntryUpdate> for geyser::EntryUpdate {
        fn from(update: &EntryUpdate) -> Self {
            Self {
                slot: update.slot,
                index: update.index,
                num_hashes: update.num_hashes,
                hash: Bytes::copy_from_slice(&update.hash),
                entry: update.entry_data.clone(),
                executed_transaction_count: update.executed_transaction_count,
            }
        }
    }

    impl From<&BlockMetadataUpdate> for geyser::BlockMetadataUpdate {
        fn from(update: &BlockMetadataUpdate) -> Self {
            Self {
                slot: update.slot,
                blockhash: Bytes::copy_from_slice(&update.blockhash),
                block_time: update.block_time,
                block_height: update.block_height,
                rewards: update.rewards.clone(),
            }
        }
    }

    /// Convert an internal Update to a protobuf StreamUpdate.
    pub fn to_stream_update(update: &Update, sequence: u64, timestamp_ns: u64) -> geyser::StreamUpdate {
        let payload = match update {
            Update::Account(u) => geyser::UpdatePayload::Account(u.into()),
            Update::Transaction(u) => geyser::UpdatePayload::Transaction(u.into()),
            Update::Slot(u) => geyser::UpdatePayload::Slot(u.into()),
            Update::Entry(u) => geyser::UpdatePayload::Entry(u.into()),
            Update::BlockMetadata(u) => geyser::UpdatePayload::BlockMetadata(u.into()),
        };

        geyser::StreamUpdate {
            sequence,
            timestamp_ns,
            payload: Some(payload),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn slot_status_conversion() {
        use geyser_tap_common::SlotStatus;
        assert_eq!(
            geyser::SlotStatus::from(SlotStatus::Processed),
            geyser::SlotStatus::Processed
        );
    }
}
